version: '3.9'

services:
  web:
    build: .
    command: sh -c "/app/.docker_compose_scripts/init_web_service.sh"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mydbuser -d url_shortener"]
      interval: 10s
      timeout: 5s
      retries: 3
