# Generated by Django 4.2.4 on 2024-06-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUrl',
            fields=[
                ('url', models.CharField(max_length=100)),
                ('custom_url', models.URLField(blank=True, default='', primary_key=True, serialize=False)),
            ],
        ),
    ]
